export const SET_CURRENT_LOCALE = 'SET_CURRENT_LOCALE'
export const SET_INIT_CURRENT_LOCALE = 'SET_INIT_CURRENT_LOCALE'
export const SET_USER_LOGGED = 'SET_USER_LOGGED'
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT'
export const SET_SOCKS = 'SET_SOCKS'

export const SET_MENUS_FILTER = 'SET_MENUS_FILTER'
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM'
